# Individual Project 2  
**Author:** Christina Porter   
**Version:** 1.0  
**Semester:** Spring 2021  
**Summary:**  For this project, I will be importing and analyzing a dataset called weather_2012.csv.

In [1]:
import pandas as pd

## Part 1:
**Initializing my data**

In [2]:
df = pd.read_csv('weather_2012.csv')

### 1.1: Getting to know the data
**Sampling my data by looking at the first lines, last lines, and a random sample of lines.**

I want to see if my data is consistent and to view the types of values that are present in the data and how the data is organized.

In [3]:
df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [4]:
df.tail()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [5]:
df.sample(5)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
771,2012-02-02 03:00:00,-5.6,-9.1,76,6,25.0,101.52,Snow Showers
8209,2012-12-08 01:00:00,2.0,-1.3,79,6,25.0,101.17,Cloudy
8033,2012-11-30 17:00:00,-9.3,-15.6,60,15,25.0,103.20,Cloudy
1337,2012-02-25 17:00:00,-3.2,-8.4,67,24,25.0,99.59,Cloudy
6230,2012-09-16 14:00:00,16.6,3.8,42,24,48.3,101.30,Mainly Clear

In [6]:
original_columns = df.columns

In [7]:
print(original_columns)

Index(['Date/Time', 'Temp (C)', 'Dew Point Temp (C)', 'Rel Hum (%)',
       'Wind Spd (km/h)', 'Visibility (km)', 'Stn Press (kPa)', 'Weather'],
      dtype='object')

## Part 2: Manipulating the Data

### 2.1: Readability

**Column Names**
The column names above are hard to read, so I want to change those to something that is easier to read.

In [8]:
col_names = ['date_time',
            'temp_c',
            'dew_point',
            'relative_humidity',
            'wind_speed',
            'visibility',
            'pressure',
            'weather']

In [9]:
df.columns = col_names

I want to test those values to make sure my new column names set properly.

In [10]:
df.head()

,date_time,temp_c,dew_point,relative_humidity,wind_speed,visibility,pressure,weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [11]:
df.describe()

,temp_c,dew_point,relative_humidity,wind_speed,visibility,pressure
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,8.798144,2.555294,67.431694,14.945469,27.664447,101.051623
std,11.687883,10.883072,16.918881,8.688696,12.622688,0.844005
min,-23.300000,-28.500000,18.000000,0.000000,0.200000,97.520000
25%,0.100000,-5.900000,56.000000,9.000000,24.100000,100.560000
50%,9.300000,3.300000,68.000000,13.000000,25.000000,101.070000
75%,18.800000,11.800000,81.000000,20.000000,25.000000,101.590000
max,33.000000,24.400000,100.000000,83.000000,48.300000,103.650000

My data has a celcius value for temperature, but I don't know much about celcius. I want to add a farenheit column so I can better understand the data.

In [12]:
df['temp_f'] = (df.temp_c*9/5) + 32

In [13]:
df.head()

,date_time,temp_c,dew_point,relative_humidity,wind_speed,visibility,pressure,weather,temp_f
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,28.76
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,28.76
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",28.76
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",29.30
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,29.30

Now, I want to rearrange these columns so my temperature values are displayed together.

In [14]:
df=df[["date_time","temp_f","temp_c","dew_point","relative_humidity","wind_speed","visibility","pressure","weather"]]

In [15]:
df.head()

,date_time,temp_f,temp_c,dew_point,relative_humidity,wind_speed,visibility,pressure,weather
0,2012-01-01 00:00:00,28.76,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,28.76,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,28.76,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,29.30,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,29.30,-1.5,-3.3,88,7,4.8,101.23,Fog

I want to view the object types of my cells so I know how to manipulate the items when working with my dataset.

In [16]:
df.dtypes

date_time             object
temp_f               float64
temp_c               float64
dew_point            float64
relative_humidity      int64
wind_speed             int64
visibility           float64
pressure             float64
weather               object
dtype: object

It will be easier for me to use my date/time values if they are in a date/time object.

In [17]:
df.date_time = pd.to_datetime(df.date_time)

In [18]:
df.dtypes

date_time            datetime64[ns]
temp_f                      float64
temp_c                      float64
dew_point                   float64
relative_humidity             int64
wind_speed                    int64
visibility                  float64
pressure                    float64
weather                      object
dtype: object

## Part 3: Analyzing the Data

### 3.1: Monthly Temperatures

Here, I want to analyze the values of my monthly temperatures. First, I'll separate my temperature values by month and find the mean temperature for each month.

In [19]:
monthly_avg = pd.DataFrame(df['temp_f'].groupby(df.date_time.dt.month).mean())

In [20]:
monthly_avg

              temp_f
date_time
1          18.731290
2          24.395000
3          37.618226
4          44.616750
5          61.227984
6          68.241250
7          73.022097
8          72.102742
9          61.672000
10         51.718952
11         33.676500
12         26.048629

Each of my months has been grouped into my index - I want to make a column for each month so it's easier to manipulate.

In [21]:
monthly_avg['month'] = monthly_avg.index

In [22]:
monthly_avg

              temp_f  month
date_time
1          18.731290      1
2          24.395000      2
3          37.618226      3
4          44.616750      4
5          61.227984      5
6          68.241250      6
7          73.022097      7
8          72.102742      8
9          61.672000      9
10         51.718952     10
11         33.676500     11
12         26.048629     12

To make this easier to read, I'm going to switch the position of my month and temperature columns.

In [23]:
monthly_avg = monthly_avg[["month","temp_f"]]

In [24]:
monthly_avg

           month     temp_f
date_time
1              1  18.731290
2              2  24.395000
3              3  37.618226
4              4  44.616750
5              5  61.227984
6              6  68.241250
7              7  73.022097
8              8  72.102742
9              9  61.672000
10            10  51.718952
11            11  33.676500
12            12  26.048629

I also want to get rid of the index name so my data is easier to read.

In [25]:
monthly_avg.index.name = None

In [26]:
monthly_avg

    month     temp_f
1       1  18.731290
2       2  24.395000
3       3  37.618226
4       4  44.616750
5       5  61.227984
6       6  68.241250
7       7  73.022097
8       8  72.102742
9       9  61.672000
10     10  51.718952
11     11  33.676500
12     12  26.048629

Now, I want to change my month representation to the string of the actual month name. To do this, I will be using a dictionary and passing it into a function that makes a list that I can pass as my new column values.

In [27]:
month_dict = {1:"January",
             2:"February",
             3:"March",
             4:"April",
             5:"May",
             6:"June",
             7:"July",
             8:"August",
             9:"September",
             10:"October",
             11:"November",
             12:"December"}

In [28]:
def convertList(dictName, convertColumn):
    listIndex = list(convertColumn)
    convertedIndex = list(map(lambda x: dictName.get(x), listIndex))
    return convertedIndex

In [29]:
monthly_avg['month'] = convertList(month_dict, monthly_avg['month'])

In [30]:
monthly_avg

        month     temp_f
1     January  18.731290
2    February  24.395000
3       March  37.618226
4       April  44.616750
5         May  61.227984
6        June  68.241250
7        July  73.022097
8      August  72.102742
9   September  61.672000
10    October  51.718952
11   November  33.676500
12   December  26.048629

### 3.2: Hourly Temperatures

Now, suppose I want to analyze the average temperature for every hour across all months.

In [31]:
hourly_avg = df['temp_f'].groupby(df.date_time.dt.hour).mean()

In [32]:
hourly_avg

date_time
0     45.623443
1     44.762787
2     43.980820
3     43.325246
4     42.744426
5     42.291967
6     42.859508
7     43.831311
8     45.280656
9     46.987213
10    48.699672
11    50.193770
12    51.541803
13    52.508689
14    53.196721
15    53.391475
16    53.178033
17    52.297705
18    51.181311
19    50.041311
20    48.848197
21    47.851803
22    47.064918
23    46.397049
Name: temp_f, dtype: float64

Since my index value represents the hour in military time, I'm going to change the index name from date_time (which is the column I pulled the time from) to Hour.

In [33]:
hourly_avg.index.name = "Hour"

In [34]:
hourly_avg

Hour
0     45.623443
1     44.762787
2     43.980820
3     43.325246
4     42.744426
5     42.291967
6     42.859508
7     43.831311
8     45.280656
9     46.987213
10    48.699672
11    50.193770
12    51.541803
13    52.508689
14    53.196721
15    53.391475
16    53.178033
17    52.297705
18    51.181311
19    50.041311
20    48.848197
21    47.851803
22    47.064918
23    46.397049
Name: temp_f, dtype: float64

Now, I also want to convert my times from military time to standard time. I will do this using the same function I used to convert my months.

In [35]:
hour_dict = {0:"12:00AM",
            1:"1:00AM",
            2:"2:00AM",
            3:"3:00AM",
            4:"4:00AM",
            5:"5:00AM",
            6:"6:00AM",
            7:"7:00AM",
            8:"8:00AM",
            9:"9:00AM",
            10:"10:00AM",
            11:"11:00AM",
            12:"12:00PM",
            13:"1:00PM",
            14:"2:00PM",
            15:"3:00PM",
            16:"4:00PM",
            17:"5:00PM",
            18:"6:00PM",
            19:"7:00PM",
            20:"8:00PM",
            21:"9:00PM",
            22:"10:00PM",
            23:"11:00PM"}

In [36]:
hourly_avg.index = convertList(hour_dict, hourly_avg.index)

In [37]:
hourly_avg

12:00AM    45.623443
1:00AM     44.762787
2:00AM     43.980820
3:00AM     43.325246
4:00AM     42.744426
5:00AM     42.291967
6:00AM     42.859508
7:00AM     43.831311
8:00AM     45.280656
9:00AM     46.987213
10:00AM    48.699672
11:00AM    50.193770
12:00PM    51.541803
1:00PM     52.508689
2:00PM     53.196721
3:00PM     53.391475
4:00PM     53.178033
5:00PM     52.297705
6:00PM     51.181311
7:00PM     50.041311
8:00PM     48.848197
9:00PM     47.851803
10:00PM    47.064918
11:00PM    46.397049
Name: temp_f, dtype: float64

### 3.3: Weather Types

Finally, I want to guage the various types of weather that have been recorded.

In [38]:
df['weather'].groupby(df['weather']).count()

weather
Clear                                      1326
Cloudy                                     1728
Drizzle                                      41
Drizzle,Fog                                  80
Drizzle,Ice Pellets,Fog                       1
Drizzle,Snow                                  2
Drizzle,Snow,Fog                             15
Fog                                         150
Freezing Drizzle                              7
Freezing Drizzle,Fog                          6
Freezing Drizzle,Haze                         3
Freezing Drizzle,Snow                        11
Freezing Fog                                  4
Freezing Rain                                14
Freezing Rain,Fog                             4
Freezing Rain,Haze                            2
Freezing Rain,Ice Pellets,Fog                 1
Freezing Rain,Snow Grains                     1
Haze                                         16
Mainly Clear                               2106
Moderate Rain,Fog                             1
Moderate Snow                                 4
Moderate Snow,Blowing Snow                    2
Mostly Cloudy                              2069
Rain                                        306
Rain Showers                                188
Rain Showers,Fog                              1
Rain Showers,Snow Showers                     2
Rain,Fog                                    116
Rain,Haze                                     3
Rain,Ice Pellets                              1
Rain,Snow                                    18
Rain,Snow Grains                              1
Rain,Snow,Fog                                 1
Rain,Snow,Ice Pellets                         4
Snow                                        390
Snow Pellets                                  1
Snow Showers                                 60
Snow Showers,Fog                              4
Snow,Blowing Snow                            19
Snow,Fog                                     37
Snow,Haze                                     5
Snow,Ice Pellets                              6
Thunderstorms                                 2
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Moderate Rain Showers,Fog       1
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers                   16
Thunderstorms,Rain Showers,Fog                3
Thunderstorms,Rain,Fog                        1
Name: weather, dtype: int64

Above we were able to condense the weather data into the different values that were used. However, notice that some rows combine multiple values which actually ends up reusing some values multiple times.

To help with this, I'm going to convert my weather values to a dataframe, move them to a column, then separate the values so that I can condense my list so it doesn't have repeating values.

In [39]:
weather = pd.DataFrame(df['weather'].groupby(df['weather']).count())

In [40]:
weather

                                         weather
weather
Clear                                       1326
Cloudy                                      1728
Drizzle                                       41
Drizzle,Fog                                   80
Drizzle,Ice Pellets,Fog                        1
Drizzle,Snow                                   2
Drizzle,Snow,Fog                              15
Fog                                          150
Freezing Drizzle                               7
Freezing Drizzle,Fog                           6
Freezing Drizzle,Haze                          3
Freezing Drizzle,Snow                         11
Freezing Fog                                   4
Freezing Rain                                 14
Freezing Rain,Fog                              4
Freezing Rain,Haze                             2
Freezing Rain,Ice Pellets,Fog                  1
Freezing Rain,Snow Grains                      1
Haze                                          16
Mainly Clear                                2106
Moderate Rain,Fog                              1
Moderate Snow                                  4
Moderate Snow,Blowing Snow                     2
Mostly Cloudy                               2069
Rain                                         306
Rain Showers                                 188
Rain Showers,Fog                               1
Rain Showers,Snow Showers                      2
Rain,Fog                                     116
Rain,Haze                                      3
Rain,Ice Pellets                               1
Rain,Snow                                     18
Rain,Snow Grains                               1
Rain,Snow,Fog                                  1
Rain,Snow,Ice Pellets                          4
Snow                                         390
Snow Pellets                                   1
Snow Showers                                  60
Snow Showers,Fog                               4
Snow,Blowing Snow                             19
Snow,Fog                                      37
Snow,Haze                                      5
Snow,Ice Pellets                               6
Thunderstorms                                  2
Thunderstorms,Heavy Rain Showers               1
Thunderstorms,Moderate Rain Showers,Fog        1
Thunderstorms,Rain                             3
Thunderstorms,Rain Showers                    16
Thunderstorms,Rain Showers,Fog                 3
Thunderstorms,Rain,Fog                         1

In [41]:
weather['weatherType'] = weather.index

In [42]:
weather

,weather,weatherType
weather,,
Clear,1326,Clear
Cloudy,1728,Cloudy
Drizzle,41,Drizzle
"Drizzle,Fog",80,"Drizzle,Fog"
"Drizzle,Ice Pellets,Fog",1,"Drizzle,Ice Pellets,Fog"
"Drizzle,Snow",2,"Drizzle,Snow"
"Drizzle,Snow,Fog",15,"Drizzle,Snow,Fog"
Fog,150,Fog
Freezing Drizzle,7,Freezing Drizzle
"Freezing Drizzle,Fog",6,"Freezing Drizzle,Fog"
"Freezing Drizzle,Haze",3,"Freezing Drizzle,Haze"
"Freezing Drizzle,Snow",11,"Freezing Drizzle,Snow"
Freezing Fog,4,Freezing Fog
Freezing Rain,14,Freezing Rain
"Freezing Rain,Fog",4,"Freezing Rain,Fog"
"Freezing Rain,Haze",2,"Freezing Rain,Haze"
"Freezing Rain,Ice Pellets,Fog",1,"Freezing Rain,Ice Pellets,Fog"
"Freezing Rain,Snow Grains",1,"Freezing Rain,Snow Grains"
Haze,16,Haze
Mainly Clear,2106,Mainly Clear
"Moderate Rain,Fog",1,"Moderate Rain,Fog"
Moderate Snow,4,Moderate Snow
"Moderate Snow,Blowing Snow",2,"Moderate Snow,Blowing Snow"
Mostly Cloudy,2069,Mostly Cloudy
Rain,306,Rain
Rain Showers,188,Rain Showers
"Rain Showers,Fog",1,"Rain Showers,Fog"
"Rain Showers,Snow Showers",2,"Rain Showers,Snow Showers"
"Rain,Fog",116,"Rain,Fog"
"Rain,Haze",3,"Rain,Haze"
"Rain,Ice Pellets",1,"Rain,Ice Pellets"
"Rain,Snow",18,"Rain,Snow"
"Rain,Snow Grains",1,"Rain,Snow Grains"
"Rain,Snow,Fog",1,"Rain,Snow,Fog"
"Rain,Snow,Ice Pellets",4,"Rain,Snow,Ice Pellets"
Snow,390,Snow
Snow Pellets,1,Snow Pellets
Snow Showers,60,Snow Showers
"Snow Showers,Fog",4,"Snow Showers,Fog"
"Snow,Blowing Snow",19,"Snow,Blowing Snow"
"Snow,Fog",37,"Snow,Fog"
"Snow,Haze",5,"Snow,Haze"
"Snow,Ice Pellets",6,"Snow,Ice Pellets"
Thunderstorms,2,Thunderstorms
"Thunderstorms,Heavy Rain Showers",1,"Thunderstorms,Heavy Rain Showers"
"Thunderstorms,Moderate Rain Showers,Fog",1,"Thunderstorms,Moderate Rain Showers,Fog"
"Thunderstorms,Rain",3,"Thunderstorms,Rain"
"Thunderstorms,Rain Showers",16,"Thunderstorms,Rain Showers"
"Thunderstorms,Rain Showers,Fog",3,"Thunderstorms,Rain Showers,Fog"
"Thunderstorms,Rain,Fog",1,"Thunderstorms,Rain,Fog"

In [43]:
weather[['Weather 1', 'Weather 2', 'Weather 3']] = weather.weatherType.str.split(",", expand = True)

In [44]:
weather

,weather,weatherType,Weather 1,Weather 2,Weather 3
weather,,,,,
Clear,1326,Clear,Clear,None,None
Cloudy,1728,Cloudy,Cloudy,None,None
Drizzle,41,Drizzle,Drizzle,None,None
"Drizzle,Fog",80,"Drizzle,Fog",Drizzle,Fog,None
"Drizzle,Ice Pellets,Fog",1,"Drizzle,Ice Pellets,Fog",Drizzle,Ice Pellets,Fog
"Drizzle,Snow",2,"Drizzle,Snow",Drizzle,Snow,None
"Drizzle,Snow,Fog",15,"Drizzle,Snow,Fog",Drizzle,Snow,Fog
Fog,150,Fog,Fog,None,None
Freezing Drizzle,7,Freezing Drizzle,Freezing Drizzle,None,None
"Freezing Drizzle,Fog",6,"Freezing Drizzle,Fog",Freezing Drizzle,Fog,None
"Freezing Drizzle,Haze",3,"Freezing Drizzle,Haze",Freezing Drizzle,Haze,None
"Freezing Drizzle,Snow",11,"Freezing Drizzle,Snow",Freezing Drizzle,Snow,None
Freezing Fog,4,Freezing Fog,Freezing Fog,None,None
Freezing Rain,14,Freezing Rain,Freezing Rain,None,None
"Freezing Rain,Fog",4,"Freezing Rain,Fog",Freezing Rain,Fog,None
"Freezing Rain,Haze",2,"Freezing Rain,Haze",Freezing Rain,Haze,None
"Freezing Rain,Ice Pellets,Fog",1,"Freezing Rain,Ice Pellets,Fog",Freezing Rain,Ice Pellets,Fog
"Freezing Rain,Snow Grains",1,"Freezing Rain,Snow Grains",Freezing Rain,Snow Grains,None
Haze,16,Haze,Haze,None,None
Mainly Clear,2106,Mainly Clear,Mainly Clear,None,None
"Moderate Rain,Fog",1,"Moderate Rain,Fog",Moderate Rain,Fog,None
Moderate Snow,4,Moderate Snow,Moderate Snow,None,None
"Moderate Snow,Blowing Snow",2,"Moderate Snow,Blowing Snow",Moderate Snow,Blowing Snow,None
Mostly Cloudy,2069,Mostly Cloudy,Mostly Cloudy,None,None
Rain,306,Rain,Rain,None,None
Rain Showers,188,Rain Showers,Rain Showers,None,None
"Rain Showers,Fog",1,"Rain Showers,Fog",Rain Showers,Fog,None
"Rain Showers,Snow Showers",2,"Rain Showers,Snow Showers",Rain Showers,Snow Showers,None
"Rain,Fog",116,"Rain,Fog",Rain,Fog,None
"Rain,Haze",3,"Rain,Haze",Rain,Haze,None
"Rain,Ice Pellets",1,"Rain,Ice Pellets",Rain,Ice Pellets,None
"Rain,Snow",18,"Rain,Snow",Rain,Snow,None
"Rain,Snow Grains",1,"Rain,Snow Grains",Rain,Snow Grains,None
"Rain,Snow,Fog",1,"Rain,Snow,Fog",Rain,Snow,Fog
"Rain,Snow,Ice Pellets",4,"Rain,Snow,Ice Pellets",Rain,Snow,Ice Pellets
Snow,390,Snow,Snow,None,None
Snow Pellets,1,Snow Pellets,Snow Pellets,None,None
Snow Showers,60,Snow Showers,Snow Showers,None,None
"Snow Showers,Fog",4,"Snow Showers,Fog",Snow Showers,Fog,None
"Snow,Blowing Snow",19,"Snow,Blowing Snow",Snow,Blowing Snow,None
"Snow,Fog",37,"Snow,Fog",Snow,Fog,None
"Snow,Haze",5,"Snow,Haze",Snow,Haze,None
"Snow,Ice Pellets",6,"Snow,Ice Pellets",Snow,Ice Pellets,None
Thunderstorms,2,Thunderstorms,Thunderstorms,None,None
"Thunderstorms,Heavy Rain Showers",1,"Thunderstorms,Heavy Rain Showers",Thunderstorms,Heavy Rain Showers,None
"Thunderstorms,Moderate Rain Showers,Fog",1,"Thunderstorms,Moderate Rain Showers,Fog",Thunderstorms,Moderate Rain Showers,Fog
"Thunderstorms,Rain",3,"Thunderstorms,Rain",Thunderstorms,Rain,None
"Thunderstorms,Rain Showers",16,"Thunderstorms,Rain Showers",Thunderstorms,Rain Showers,None
"Thunderstorms,Rain Showers,Fog",3,"Thunderstorms,Rain Showers,Fog",Thunderstorms,Rain Showers,Fog
"Thunderstorms,Rain,Fog",1,"Thunderstorms,Rain,Fog",Thunderstorms,Rain,Fog

In [45]:
uniqueWeather = list(pd.unique(weather[['Weather 1', 'Weather 2', 'Weather 3']].values.ravel()))

In [46]:
uniqueWeather

['Clear',
 None,
 'Cloudy',
 'Drizzle',
 'Fog',
 'Ice Pellets',
 'Snow',
 'Freezing Drizzle',
 'Haze',
 'Freezing Fog',
 'Freezing Rain',
 'Snow Grains',
 'Mainly Clear',
 'Moderate Rain',
 'Moderate Snow',
 'Blowing Snow',
 'Mostly Cloudy',
 'Rain',
 'Rain Showers',
 'Snow Showers',
 'Snow Pellets',
 'Thunderstorms',
 'Heavy Rain Showers',
 'Moderate Rain Showers']

An unfortunate circumstance of separating my data the way I did was that I had some N/A values since each data value didn't have the same amount of delimited values. To manipulate this data further, I want to get rid of those nonexistent values.

In [47]:
uniqueWeather.remove(None)

In [48]:
uniqueWeather

['Clear',
 'Cloudy',
 'Drizzle',
 'Fog',
 'Ice Pellets',
 'Snow',
 'Freezing Drizzle',
 'Haze',
 'Freezing Fog',
 'Freezing Rain',
 'Snow Grains',
 'Mainly Clear',
 'Moderate Rain',
 'Moderate Snow',
 'Blowing Snow',
 'Mostly Cloudy',
 'Rain',
 'Rain Showers',
 'Snow Showers',
 'Snow Pellets',
 'Thunderstorms',
 'Heavy Rain Showers',
 'Moderate Rain Showers']

In [49]:
uniqueWeather.sort()

In [50]:
uniqueWeather

['Blowing Snow',
 'Clear',
 'Cloudy',
 'Drizzle',
 'Fog',
 'Freezing Drizzle',
 'Freezing Fog',
 'Freezing Rain',
 'Haze',
 'Heavy Rain Showers',
 'Ice Pellets',
 'Mainly Clear',
 'Moderate Rain',
 'Moderate Rain Showers',
 'Moderate Snow',
 'Mostly Cloudy',
 'Rain',
 'Rain Showers',
 'Snow',
 'Snow Grains',
 'Snow Pellets',
 'Snow Showers',
 'Thunderstorms']

## Part 4: Saving the Data

Now that we are finished analyzing our data, we want to go ahead and convert it back into its original form and save our analysis to a csv.

### 4.1: Converting back to Original Format

In [51]:
original_columns = list(original_columns)

In [52]:
original_columns

['Date/Time',
 'Temp (C)',
 'Dew Point Temp (C)',
 'Rel Hum (%)',
 'Wind Spd (km/h)',
 'Visibility (km)',
 'Stn Press (kPa)',
 'Weather']

In [53]:
original_columns.insert(1, 'Temp (F)')

In [54]:
original_columns

['Date/Time',
 'Temp (F)',
 'Temp (C)',
 'Dew Point Temp (C)',
 'Rel Hum (%)',
 'Wind Spd (km/h)',
 'Visibility (km)',
 'Stn Press (kPa)',
 'Weather']

In [55]:
df.columns = original_columns

In [56]:
df.head()

,Date/Time,Temp (F),Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,28.76,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,28.76,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,28.76,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,29.30,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,29.30,-1.5,-3.3,88,7,4.8,101.23,Fog

### 4.2: Saving the Analysis

In [57]:
df.to_csv('weather_2012_new.csv', index = False)

In [58]:
monthly_avg.to_csv('monthly_avg.csv', index = False)

In [59]:
hourly_avg.to_csv('hourly_avg.csv')

In [60]:
#end of notebook